export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_ID = "GET_COUNTRY_ID";
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";